pipeline {
    agent any
    stages {
         stage('Clone repository') { 
            steps { 
                checkout scm
            }
        }

        stage('Build') { 
            steps { 
                script{
                 app = docker.build("testapp-cicd")
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
	stage('Execute playbook'){
		steps {
			withCredentials([aws(credentialsId: "06820e6f-366a-4e85-9fcc-12cc90ce5d79")]) {
				ansiblePlaybook playbook:'ansible/create-infra.yaml'
			}
		}
	}
        stage('Deploy') {
            steps {
                script{
			withCredentials([aws(credentialsId: "06820e6f-366a-4e85-9fcc-12cc90ce5d79")]) {
			
			}
                    }
                }
            }
        }
    }
