---
- name: Create AWS infrastructure.
  hosts: localhost

  tasks:
    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        name: "Valeriya-FWS-TestInstance-App"
        key_name: 'k8s-valeriya'
        exact_count: 1
        region: us-east-1
        vpc_subnet_id: 'subnet-0992c1cd4b004598c'
        network:
          assign_public_ip: true
          security_group: 'sg-0f152bcdb1c680b0e'
        instance_type: 't2.micro'
          #image_id: 'ami-0e86e20dae9224db8'
          #need to run it on RHEL image, so:
        image_id: 'ami-0583d8c7a9c35822c'
        state: present
