---
- name: Destroy infra
  hosts: app

  tasks:
    - name: remove the EC2 instance
      amazon.aws.ec2_instance:
        state: absent
        filters:
          instance-state-name: running
      delegate_to: localhost

